networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - pocketbase
      - solid
    networks:
      - dev

  solid:
    build:
      context: .
      dockerfile: ./dockerfile.solid
    links:
      - pocketbase
    volumes: 
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    networks:
      - dev

  pocketbase:
    build:
      context: .
      dockerfile: ./dockerfile.pocketbase
    volumes:
      - /path/to/data:/pb_data
    ports:
      - 8080:8080
    networks:
      - dev
